ALTER TABLE [dbo].[USERDATA] ALTER COLUMN [strSkill] VARCHAR (20)
ALTER TABLE [dbo].[USERDATA] ALTER COLUMN [strItem] VARCHAR (400)
ALTER TABLE [dbo].[USERDATA] ALTER COLUMN [strSerial] VARCHAR (400)
