DROP TABLE
MONSTER_ITEM_TEST,
K_NPCPOS_BACK,
-- We can drop it and in case someone wants to use the EXEC_NPCPOS_SORT procedure, it will recreate it on their local db.
K_NPCPOS_SORT,

BLOCKED_USERDATA,
BLOCKED_WAREHOUSE,

-- There are better ways in creating db backups. It doesn't make sense to maintain this code in here, let's remove it:
BK_MON_USERDATA,
BK_MON_WAREHOUSE,
BK_TUE_USERDATA,
BK_TUE_WAREHOUSE,
BK_WED_USERDATA,
BK_WED_WAREHOUSE,
BK_THU_USERDATA,
BK_THU_WAREHOUSE,
BK_FRI_USERDATA,
BK_FRI_WAREHOUSE,
BK_SAT_USERDATA,
BK_SAT_WAREHOUSE,
BK_SUN_USERDATA,
BK_SUN_WAREHOUSE;


DROP PROCEDURE
BACKUP_MON,
BACKUP_TUE,
BACKUP_WED,
BACKUP_THU,
BACKUP_FRI,
BACKUP_SAT,
BACKUP_SUN,
BACKUP_USERDATA,
BACKUP_WAREHOUSE,
EXEC_SEARCH_USER_ITEM,
LEVEL_CHEAT;
