SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCOUNT_CHAR](
	[strAccountID] [varchar](21) NOT NULL,
	[bNation] [tinyint] NOT NULL,
	[bCharNum] [tinyint] NOT NULL,
	[strCharID1] [varchar](21) NULL,
	[strCharID2] [varchar](21) NULL,
	[strCharID3] [varchar](21) NULL,
	[strCharID4] [varchar](21) NULL,
	[strCharID5] [varchar](21) NULL,
 CONSTRAINT [PK_ACCOUNT_CHAR] PRIMARY KEY CLUSTERED 
(
	[strAccountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACCOUNT_CHAR] ADD  CONSTRAINT [DF_ACCOUNT_CHAR_bCharNum]  DEFAULT ((0)) FOR [bCharNum]
GO
