SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BK_FRI_WAREHOUSE](
	[strAccountID] [char](21) NOT NULL,
	[nMoney] [int] NOT NULL,
	[warehouseData] [varchar](1600) NULL,
 CONSTRAINT [PK_BK_FRI_WAREHOUSE] PRIMARY KEY CLUSTERED 
(
	[strAccountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
