SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEM_GROUP](
	[group] [smallint] NOT NULL,
	[name] [varchar](30) NULL,
	[item1] [int] NOT NULL,
	[item2] [int] NOT NULL,
	[item3] [int] NOT NULL,
	[item4] [int] NOT NULL,
	[item5] [int] NOT NULL,
	[item6] [int] NOT NULL,
	[item7] [int] NOT NULL,
	[item8] [int] NOT NULL,
	[item9] [int] NOT NULL,
	[item10] [int] NOT NULL,
	[item11] [int] NOT NULL,
	[item12] [int] NOT NULL,
	[item13] [int] NOT NULL,
	[item14] [int] NOT NULL,
	[item15] [int] NOT NULL,
	[item16] [int] NOT NULL,
	[item17] [int] NOT NULL,
	[item18] [int] NOT NULL,
	[item19] [int] NOT NULL,
	[item20] [int] NOT NULL,
	[item21] [int] NOT NULL,
	[item22] [int] NOT NULL,
	[item23] [int] NOT NULL,
	[item24] [int] NOT NULL,
	[item25] [int] NOT NULL,
	[item26] [int] NOT NULL,
	[item27] [int] NOT NULL,
	[item28] [int] NOT NULL,
	[item29] [int] NOT NULL,
	[item30] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item1]  DEFAULT ((0)) FOR [item1]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item2]  DEFAULT ((0)) FOR [item2]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item3]  DEFAULT ((0)) FOR [item3]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item4]  DEFAULT ((0)) FOR [item4]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item5]  DEFAULT ((0)) FOR [item5]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item6]  DEFAULT ((0)) FOR [item6]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item7]  DEFAULT ((0)) FOR [item7]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item8]  DEFAULT ((0)) FOR [item8]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item9]  DEFAULT ((0)) FOR [item9]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item10]  DEFAULT ((0)) FOR [item10]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item11]  DEFAULT ((0)) FOR [item11]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item12]  DEFAULT ((0)) FOR [item12]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item13]  DEFAULT ((0)) FOR [item13]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item14]  DEFAULT ((0)) FOR [item14]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item15]  DEFAULT ((0)) FOR [item15]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item16]  DEFAULT ((0)) FOR [item16]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item17]  DEFAULT ((0)) FOR [item17]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item18]  DEFAULT ((0)) FOR [item18]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item19]  DEFAULT ((0)) FOR [item19]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item20]  DEFAULT ((0)) FOR [item20]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item21]  DEFAULT ((0)) FOR [item21]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item22]  DEFAULT ((0)) FOR [item22]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item23]  DEFAULT ((0)) FOR [item23]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item24]  DEFAULT ((0)) FOR [item24]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item25]  DEFAULT ((0)) FOR [item25]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item26]  DEFAULT ((0)) FOR [item26]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item27]  DEFAULT ((0)) FOR [item27]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item28]  DEFAULT ((0)) FOR [item28]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item29]  DEFAULT ((0)) FOR [item29]
GO
ALTER TABLE [dbo].[ITEM_GROUP] ADD  CONSTRAINT [DF_ITEM_GROUP_item30]  DEFAULT ((0)) FOR [item30]
GO
