SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAKE_ITEM_LARECODE](
	[byLevelGrade] [tinyint] NOT NULL,
	[sLareItem] [smallint] NOT NULL,
	[sMagicItem] [smallint] NOT NULL,
	[sGereralItem] [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAKE_ITEM_LARECODE] ADD  CONSTRAINT [DF_MAKE_ITEM_LARECODE_sLareItem]  DEFAULT ((0)) FOR [sLareItem]
GO
ALTER TABLE [dbo].[MAKE_ITEM_LARECODE] ADD  CONSTRAINT [DF_MAKE_ITEM_LARECODE_sMagicItem]  DEFAULT ((0)) FOR [sMagicItem]
GO
ALTER TABLE [dbo].[MAKE_ITEM_LARECODE] ADD  CONSTRAINT [DF_MAKE_ITEM_LARECODE_sGereralItem]  DEFAULT ((0)) FOR [sGereralItem]
GO
