SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAKE_ITEM_GROUP](
    [iItemGroupNum] [int] IDENTITY(100,1) NOT NULL,
    [iItem_01] [int] NULL,
    [sPersent01] [smallint] NULL CONSTRAINT DF_sPersent01 DEFAULT ((0)),
    [iItem_02] [int] NULL,
    [sPersent02] [smallint] NULL CONSTRAINT DF_sPersent02 DEFAULT ((0)),
    [iItem_03] [int] NULL,
    [sPersent03] [smallint] NULL CONSTRAINT DF_sPersent03 DEFAULT ((0)),
    [iItem_04] [int] NULL,
    [sPersent04] [smallint] NULL CONSTRAINT DF_sPersent04 DEFAULT ((0)),
    [iItem_05] [int] NULL,
    [sPersent05] [smallint] NULL CONSTRAINT DF_sPersent05 DEFAULT ((0)),
    [iItem_06] [int] NULL,
    [sPersent06] [smallint] NULL CONSTRAINT DF_sPersent06 DEFAULT ((0)),
    [iItem_07] [int] NULL,
    [sPersent07] [smallint] NULL CONSTRAINT DF_sPersent07 DEFAULT ((0)),
    [iItem_08] [int] NULL,
    [sPersent08] [smallint] NULL CONSTRAINT DF_sPersent08 DEFAULT ((0)),
    [iItem_09] [int] NULL,
    [sPersent09] [smallint] NULL CONSTRAINT DF_sPersent09 DEFAULT ((0)),
    [iItem_10] [int] NULL,
    [sPersent10] [smallint] NULL CONSTRAINT DF_sPersent10 DEFAULT ((0)),
    [iItem_11] [int] NULL,
    [sPersent11] [smallint] NULL CONSTRAINT DF_sPersent11 DEFAULT ((0)),
    [iItem_12] [int] NULL,
    [sPersent12] [smallint] NULL CONSTRAINT DF_sPersent12 DEFAULT ((0)),
    [iItem_13] [int] NULL,
    [sPersent13] [smallint] NULL CONSTRAINT DF_sPersent13 DEFAULT ((0)),
    [iItem_14] [int] NULL,
    [sPersent14] [smallint] NULL CONSTRAINT DF_sPersent14 DEFAULT ((0)),
    [iItem_15] [int] NULL,
    [sPersent15] [smallint] NULL CONSTRAINT DF_sPersent15 DEFAULT ((0)),
    [iItem_16] [int] NULL,
    [sPersent16] [smallint] NULL CONSTRAINT DF_sPersent16 DEFAULT ((0)),
    [iItem_17] [int] NULL,
    [sPersent17] [smallint] NULL CONSTRAINT DF_sPersent17 DEFAULT ((0)),
    [iItem_18] [int] NULL,
    [sPersent18] [smallint] NULL CONSTRAINT DF_sPersent18 DEFAULT ((0)),
    [iItem_19] [int] NULL,
    [sPersent19] [smallint] NULL CONSTRAINT DF_sPersent19 DEFAULT ((0)),
    [iItem_20] [int] NULL,
    [sPersent20] [smallint] NULL CONSTRAINT DF_sPersent20 DEFAULT ((0)),
    [iItem_21] [int] NULL,
    [sPersent21] [smallint] NULL CONSTRAINT DF_sPersent21 DEFAULT ((0)),
    [iItem_22] [int] NULL,
    [sPersent22] [smallint] NULL CONSTRAINT DF_sPersent22 DEFAULT ((0)),
    [iItem_23] [int] NULL,
    [sPersent23] [smallint] NULL CONSTRAINT DF_sPersent23 DEFAULT ((0)),
    [iItem_24] [int] NULL,
    [sPersent24] [smallint] NULL CONSTRAINT DF_sPersent24 DEFAULT ((0)),
    [iItem_25] [int] NULL,
    [sPersent25] [smallint] NULL CONSTRAINT DF_sPersent25 DEFAULT ((0)),
    [iItem_26] [int] NULL,
    [sPersent26] [smallint] NULL CONSTRAINT DF_sPersent26 DEFAULT ((0)),
    [iItem_27] [int] NULL,
    [sPersent27] [smallint] NULL CONSTRAINT DF_sPersent27 DEFAULT ((0)),
    [iItem_28] [int] NULL,
    [sPersent28] [smallint] NULL CONSTRAINT DF_sPersent28 DEFAULT ((0)),
    [iItem_29] [int] NULL,
    [sPersent29] [smallint] NULL CONSTRAINT DF_sPersent29 DEFAULT ((0)),
    [iItem_30] [int] NULL,
    [sPersent30] [smallint] NULL CONSTRAINT DF_sPersent30 DEFAULT ((0)),
    CONSTRAINT PK_iItemGroupNum PRIMARY KEY ([iItemGroupNum])
) ON [PRIMARY];
GO