SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERDATA](
	[strUserId] [char](21) NOT NULL,
	[Nation] [tinyint] NOT NULL,
	[Race] [tinyint] NOT NULL,
	[Class] [smallint] NOT NULL,
	[HairColor] [tinyint] NOT NULL,
	[Rank] [tinyint] NOT NULL,
	[Title] [tinyint] NOT NULL,
	[Level] [tinyint] NOT NULL,
	[Exp] [int] NOT NULL,
	[Loyalty] [int] NOT NULL,
	[Face] [tinyint] NOT NULL,
	[City] [tinyint] NOT NULL,
	[Knights] [smallint] NOT NULL,
	[Fame] [tinyint] NOT NULL,
	[Hp] [smallint] NOT NULL,
	[Mp] [smallint] NOT NULL,
	[Sp] [smallint] NOT NULL,
	[Strong] [tinyint] NOT NULL,
	[Sta] [tinyint] NOT NULL,
	[Dex] [tinyint] NOT NULL,
	[Intel] [tinyint] NOT NULL,
	[Cha] [tinyint] NOT NULL,
	[Authority] [tinyint] NOT NULL,
	[Points] [tinyint] NOT NULL,
	[Gold] [int] NOT NULL,
	[Zone] [tinyint] NOT NULL,
	[Bind] [smallint] NULL,
	[PX] [int] NOT NULL,
	[PZ] [int] NOT NULL,
	[PY] [int] NOT NULL,
	[dwTime] [int] NOT NULL,
	[strSkill] [varchar](10) NULL,
	[strItem] [binary](400) NULL,
	[strSerial] [binary](400) NULL,
 CONSTRAINT [PK_USERDATA] PRIMARY KEY CLUSTERED 
(
	[strUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [PK_Knights] ON [dbo].[USERDATA]
(
	[Knights] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Nation]  DEFAULT (0) FOR [Nation]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Race]  DEFAULT (1) FOR [Race]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Class]  DEFAULT (0) FOR [Class]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Gender]  DEFAULT (0) FOR [HairColor]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Rank]  DEFAULT (0) FOR [Rank]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Title]  DEFAULT (0) FOR [Title]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Level]  DEFAULT (1) FOR [Level]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Exp]  DEFAULT (0) FOR [Exp]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Loyalty]  DEFAULT (0) FOR [Loyalty]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Religion]  DEFAULT (0) FOR [Face]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_City]  DEFAULT (0) FOR [City]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Knights]  DEFAULT (0) FOR [Knights]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Fame]  DEFAULT (0) FOR [Fame]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Hp]  DEFAULT (100) FOR [Hp]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Mp]  DEFAULT (100) FOR [Mp]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Sp]  DEFAULT (100) FOR [Sp]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Str]  DEFAULT (0) FOR [Strong]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Sta]  DEFAULT (0) FOR [Sta]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Dex]  DEFAULT (0) FOR [Dex]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Intel]  DEFAULT (0) FOR [Intel]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Cha]  DEFAULT (0) FOR [Cha]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Authority]  DEFAULT (1) FOR [Authority]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Points]  DEFAULT (0) FOR [Points]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Gold]  DEFAULT (0) FOR [Gold]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_Zone]  DEFAULT (1) FOR [Zone]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_PX]  DEFAULT (268100) FOR [PX]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_PZ]  DEFAULT (131000) FOR [PZ]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_PY]  DEFAULT (0) FOR [PY]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_dwTime]  DEFAULT (0) FOR [dwTime]
GO
ALTER TABLE [dbo].[USERDATA] ADD  CONSTRAINT [DF_USERDATA_strSkill]  DEFAULT (0x00) FOR [strSkill]
GO
