SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ZONE_INFO](
	[ServerNo] [tinyint] NOT NULL,
	[ZoneNo] [smallint] NOT NULL,
	[strZoneName] [char](30) NOT NULL,
	[InitX] [int] NOT NULL,
	[InitZ] [int] NOT NULL,
	[InitY] [int] NOT NULL,
	[Type] [tinyint] NOT NULL,
	[RoomEvent] [tinyint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ZONE_INFO] ADD  CONSTRAINT [DF_ZONE_INFO2_ServerNo]  DEFAULT (1) FOR [ServerNo]
GO
ALTER TABLE [dbo].[ZONE_INFO] ADD  CONSTRAINT [DF_ZONE_INFO2_InitX]  DEFAULT (1000) FOR [InitX]
GO
ALTER TABLE [dbo].[ZONE_INFO] ADD  CONSTRAINT [DF_ZONE_INFO2_InitZ]  DEFAULT (1000) FOR [InitZ]
GO
ALTER TABLE [dbo].[ZONE_INFO] ADD  CONSTRAINT [DF_ZONE_INFO2_InitY]  DEFAULT (0) FOR [InitY]
GO
ALTER TABLE [dbo].[ZONE_INFO] ADD  CONSTRAINT [DF_ZONE_INFO2_Type]  DEFAULT (1) FOR [Type]
GO
